name: Release develop

on:
  push:
    branches:
      - develop

jobs:
  release_develop:
    runs-on: ubuntu-latest
    steps:
      - name: checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environement
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Check version
        run: yarn checkVersion

      - name: Make sure testcases passed
        run: yarn test

      - name: Make sure code don't have linter errors
        run: yarn lint

      - name: Release develop
        run: |
          git checkout --detach
          yarn build
          git add -f ./dist
          yarn release:develop
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
